[
  {
      "id": 25167,
      "campus": "hr-sfo",
      "name": "Camo Onesie",
      "slogan": "Blend in to your crowd",
      "description": "The So Fatigues will wake you up and fit you in. This high energy camo will have you blending in to even the wildest surroundings.",
      "category": "Jackets",
      "default_price": "140.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25168,
      "campus": "hr-sfo",
      "name": "Bright Future Sunglasses",
      "slogan": "You've got to wear shades",
      "description": "Where you're going you might not need roads, but you definitely need some shades. Give those baby blues a rest and let the future shine bright on these timeless lenses.",
      "category": "Accessories",
      "default_price": "69.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25169,
      "campus": "hr-sfo",
      "name": "Morning Joggers",
      "slogan": "Make yourself a morning person",
      "description": "Whether you're a morning person or not.  Whether you're gym bound or not.  Everyone looks good in joggers.",
      "category": "Pants",
      "default_price": "40.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25170,
      "campus": "hr-sfo",
      "name": "Slacker's Slacks",
      "slogan": "Comfortable for everything, or nothing",
      "description": "I'll tell you how great they are after I nap for a bit.",
      "category": "Pants",
      "default_price": "65.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25171,
      "campus": "hr-sfo",
      "name": "Heir Force Ones",
      "slogan": "A sneaker dynasty",
      "description": "Now where da boxes where I keep mine? You should peep mine, maybe once or twice but never three times. I'm just a sneaker pro, I love Pumas and shell toes, but can't nothin compare to a fresh crispy white pearl",
      "category": "Kicks",
      "default_price": "99.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25172,
      "campus": "hr-sfo",
      "name": "Pumped Up Kicks",
      "slogan": "Faster than a just about anything",
      "description": "The Pumped Up serves up crisp court style with a modern look. These shoes show off tennis-whites shades and are constructed with a supple leather upper and a classic rubber cupsole.",
      "category": "Kicks",
      "default_price": "89.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25173,
      "campus": "hr-sfo",
      "name": "Blues Suede Shoes",
      "slogan": "2019 Stanley Cup Limited Edition",
      "description": "Touch down in the land of the Delta Blues in the middle of the pouring rain",
      "category": "Dress Shoes",
      "default_price": "120.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25174,
      "campus": "hr-sfo",
      "name": "YEasy 350",
      "slogan": "Just jumped over jumpman",
      "description": "These stretchy knit shoes show off asymmetrical lacing and a big sculpted rubber midsole. In a nod to adidas soccer heritage.",
      "category": "Kicks",
      "default_price": "450.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25175,
      "campus": "hr-sfo",
      "name": "Summer Shoes",
      "slogan": "A risky call in the spring or fall",
      "description": "Low-top panelled buffed leather and mesh sneakers. Sizing embroidered in black at round toe. Tonal lace-up closure. Pull-loop and rubberized style name at padded tongue. Padded collar. Pull-loop at heel collar. Logo embroidered in black at outer side. Tonal treaded rubber sole. Tonal stitching.",
      "category": "Kicks",
      "default_price": "59.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25176,
      "campus": "hr-sfo",
      "name": "Infinity Stone",
      "slogan": "Reality is often disappointing. That is, it was. Now, reality can be whatever I want.",
      "description": "The Infinity Stones are six immensely powerful stone-like objects tied to different aspects of the universe, created by the Cosmic Entities. Each of the stones possesses unique capabilities that have been enhanced and altered by various alien civilizations for millennia.",
      "category": "Accessories",
      "default_price": "50000000.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25177,
      "campus": "hr-sfo",
      "name": "Air Minis 250",
      "slogan": "Full court support",
      "description": "This optimized air cushion pocket reduces impact but keeps a perfect balance underfoot.",
      "category": "Basketball Shoes",
      "default_price": "49.00",
      "created_at": "2021-06-02T16:53:33.359Z",
      "updated_at": "2021-06-02T16:53:33.359Z"
  },
  {
      "id": 25178,
      "campus": "hr-sfo",
      "name": "Edgardo Skirt",
      "slogan": "Eligendi molestiae ut iste et autem quod.",
      "description": "Quidem eius ex ut autem veniam. Saepe debitis ipsam reiciendis et. Doloremque aspernatur molestiae delectus. Necessitatibus dolor qui tempore error minima dolores. Quidem atque facilis corrupti.",
      "category": "Skirt",
      "default_price": "168.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25179,
      "campus": "hr-sfo",
      "name": "Kevon Suit",
      "slogan": "Alias inventore commodi voluptas consectetur quos dolor neque.",
      "description": "Tenetur a eius sed in et. Eaque omnis omnis illum eaque voluptatem sed tempore enim ducimus. Ut ipsum in. Commodi nulla alias aut.",
      "category": "Suit",
      "default_price": "93.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25180,
      "campus": "hr-sfo",
      "name": "Cloyd Sweatpants",
      "slogan": "Doloribus non eos officia labore molestiae quae ipsam praesentium.",
      "description": "Quidem aspernatur doloremque. Itaque placeat error hic et nostrum animi qui. Quia molestiae accusamus blanditiis. Ipsam ea aspernatur sit omnis.",
      "category": "Sweatpants",
      "default_price": "797.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25181,
      "campus": "hr-sfo",
      "name": "Erwin Hoodie",
      "slogan": "Quas qui fugit sunt laboriosam doloribus iure ut.",
      "description": "Non sit nesciunt odio cumque blanditiis repellat. Delectus dolores nisi perferendis. Ea ab est nobis animi nobis est incidunt.",
      "category": "Hoodie",
      "default_price": "252.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25182,
      "campus": "hr-sfo",
      "name": "Arnaldo Dress",
      "slogan": "Explicabo quod sunt voluptatum sed voluptatem.",
      "description": "Perspiciatis quod officia sed. Velit consequatur consequatur et atque non beatae in. Non velit molestias magni iure officiis corporis magnam. Saepe impedit est sed sed sequi eos et in. Ut et illo vitae quis et et.",
      "category": "Dress",
      "default_price": "867.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25183,
      "campus": "hr-sfo",
      "name": "Winston Tank Top",
      "slogan": "Minus iusto et accusantium facere dolores dolorem quia magnam velit.",
      "description": "Occaecati in iste doloribus earum cum. Corrupti similique autem et. At dicta assumenda reiciendis. Reiciendis et sit eligendi officia ipsa dolor quia eveniet aut. Doloribus ut incidunt laboriosam aperiam eius id non veritatis.",
      "category": "Tank Top",
      "default_price": "819.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25184,
      "campus": "hr-sfo",
      "name": "Garret Backpack",
      "slogan": "Ipsa tempore maxime minima deleniti nihil non et.",
      "description": "Non eos voluptate sed doloribus. Ut atque est voluptas temporibus ut ea est. Perferendis cumque sint enim. In voluptas nostrum aut neque occaecati neque ea ducimus. Molestiae sit et tempore in dolor corrupti. Quaerat iusto fugiat tempore possimus quis dolores rerum hic.",
      "category": "Backpack",
      "default_price": "698.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25185,
      "campus": "hr-sfo",
      "name": "Jovanny Hoodie",
      "slogan": "Hic voluptatum saepe iure magnam aut enim consequatur veniam.",
      "description": "Et beatae optio. Voluptatem nam nostrum velit sed repudiandae qui est. Blanditiis non quod sequi asperiores voluptates quas a. Ducimus saepe aliquid. Aut totam nihil omnis. Reiciendis a est mollitia dicta minus.",
      "category": "Hoodie",
      "default_price": "869.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25186,
      "campus": "hr-sfo",
      "name": "The Jaron Sunglasses",
      "slogan": "Aliquid saepe voluptatibus quis.",
      "description": "Enim et temporibus laudantium sed. Debitis ratione in autem corporis accusantium. Aperiam est vel ratione unde.",
      "category": "Sunglasses",
      "default_price": "613.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25187,
      "campus": "hr-sfo",
      "name": "Stone Shirt",
      "slogan": "Pariatur et ab et molestiae quibusdam quasi iure voluptas.",
      "description": "Maxime tempore optio in id. Sed ea enim. Tempora harum non dolor qui assumenda fugiat at recusandae.",
      "category": "Shirt",
      "default_price": "130.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25188,
      "campus": "hr-sfo",
      "name": "The Verda Pants",
      "slogan": "Consequatur quas nemo molestiae omnis.",
      "description": "Est possimus vel non dolore perferendis quia. Est voluptatem ex odit doloremque molestiae nulla modi repudiandae necessitatibus. Enim impedit quos et autem pariatur totam et perferendis. Voluptas molestiae delectus non ut. Minima qui dolorem repellendus est ex dolorem non.",
      "category": "Pants",
      "default_price": "401.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25189,
      "campus": "hr-sfo",
      "name": "Webster Tank Top",
      "slogan": "Libero accusamus ea est ut culpa vel et voluptas velit.",
      "description": "Reprehenderit ea facere. Odio sunt inventore. Rerum cum autem tempora amet enim aut error corporis.",
      "category": "Tank Top",
      "default_price": "495.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25190,
      "campus": "hr-sfo",
      "name": "Ahmad 1650 Hoodie",
      "slogan": "Nam qui et molestiae.",
      "description": "Accusamus nesciunt et. Quibusdam et ipsam accusantium sit et debitis. Quia porro tempora et ut ab aut rerum. Dicta saepe non dolor rerum quasi deleniti sed explicabo perferendis.",
      "category": "Hoodie",
      "default_price": "289.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25191,
      "campus": "hr-sfo",
      "name": "Lennie Boots",
      "slogan": "Aut accusamus ut sed.",
      "description": "Omnis voluptatem quasi reiciendis distinctio molestiae autem reiciendis. Perspiciatis eum dolores sed ipsam dolores. Accusantium est dolorem. Animi perferendis laboriosam ex. Et consequatur quis et ducimus ipsa voluptas.",
      "category": "Boots",
      "default_price": "297.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25192,
      "campus": "hr-sfo",
      "name": "Jett Hat",
      "slogan": "Quia saepe non provident laboriosam molestiae reiciendis.",
      "description": "Quia consequatur eum est. Voluptatem aut architecto nemo. Impedit deleniti sunt reiciendis rerum voluptatum optio tempora autem tempore. At deleniti incidunt quidem. Aspernatur impedit repellat optio doloremque et ut.",
      "category": "Hat",
      "default_price": "18.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25193,
      "campus": "hr-sfo",
      "name": "Adolfo Shorts",
      "slogan": "Vitae odit aliquid sed unde voluptate error ullam.",
      "description": "Exercitationem qui quia omnis laudantium itaque. Debitis consequatur voluptatibus sed cumque sed doloribus molestias. Ipsum rem est autem facere excepturi vel ducimus. Labore aut explicabo quis quia autem sit id. Voluptas amet quis.",
      "category": "Shorts",
      "default_price": "127.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25194,
      "campus": "hr-sfo",
      "name": "Gilbert Skirt",
      "slogan": "Maiores est eos itaque et et quia officia vero et.",
      "description": "Voluptas voluptatum rerum. Molestiae explicabo dolor suscipit nihil consequuntur necessitatibus molestiae cupiditate. Id et enim. Quos facilis quasi optio qui.",
      "category": "Skirt",
      "default_price": "582.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25195,
      "campus": "hr-sfo",
      "name": "Greyson Skirt",
      "slogan": "Recusandae est dolorem earum aut eum ipsum amet ad labore.",
      "description": "Rerum laborum minima enim facere facilis consequatur temporibus commodi. Consequatur exercitationem enim sapiente quod voluptas. Veniam sint ullam quis sequi officiis aut deleniti dolor a.",
      "category": "Skirt",
      "default_price": "140.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25196,
      "campus": "hr-sfo",
      "name": "Arianna 1500 Backpack",
      "slogan": "Minus blanditiis et omnis voluptatem quod consequatur assumenda assumenda eligendi.",
      "description": "Debitis rerum rerum labore aliquam fugiat sunt sunt est. Voluptas voluptas sunt saepe a voluptatem quia facere molestiae adipisci. Aut nobis voluptatem quia.",
      "category": "Backpack",
      "default_price": "481.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25197,
      "campus": "hr-sfo",
      "name": "Xavier Sweater",
      "slogan": "Sit et sed.",
      "description": "Consequuntur aperiam est ducimus facilis. Quo minus ut ut. Sequi illo iure velit nihil omnis. Cum est vel aut sed voluptatem.",
      "category": "Sweater",
      "default_price": "493.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25198,
      "campus": "hr-sfo",
      "name": "The Cara Boots",
      "slogan": "Aliquid eveniet iure qui provident.",
      "description": "Nobis sint est id ex deserunt tempora cupiditate. Consequatur modi quia qui omnis placeat veniam voluptatem molestias et. Tempora sunt culpa minima sed quia atque voluptatibus autem. Expedita ipsa tenetur quia totam iste iusto.",
      "category": "Boots",
      "default_price": "596.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25199,
      "campus": "hr-sfo",
      "name": "Scotty Dress",
      "slogan": "Sequi aut sit fugiat eaque dignissimos quia delectus quo.",
      "description": "Autem modi sed. Molestiae repudiandae asperiores et voluptate voluptates voluptas nihil velit. Ipsa beatae voluptas. Quia recusandae exercitationem voluptas ex aut hic alias. Quia quia perferendis iste assumenda omnis eligendi explicabo quo. Corporis eaque qui qui.",
      "category": "Dress",
      "default_price": "810.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25200,
      "campus": "hr-sfo",
      "name": "Tyrique Coat",
      "slogan": "Ut quo amet iusto molestiae.",
      "description": "Vel voluptatem delectus enim id unde. Impedit consequatur explicabo id qui natus libero. Incidunt quisquam quas odit aliquam quis molestiae consequatur. Nemo eos quo omnis molestias eveniet sunt repellat qui. Ipsum dicta ut quod perspiciatis omnis tenetur.",
      "category": "Coat",
      "default_price": "590.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25201,
      "campus": "hr-sfo",
      "name": "Asa Slacks",
      "slogan": "Est aliquam maiores nemo repellendus est tempore fugit exercitationem quisquam.",
      "description": "Voluptates pariatur aliquam id consequuntur. Quis officiis doloremque qui deleniti praesentium. Sit qui maxime rerum alias at sit tempora. Error ipsum laboriosam debitis. Adipisci eligendi temporibus laudantium beatae aut enim.",
      "category": "Slacks",
      "default_price": "263.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25202,
      "campus": "hr-sfo",
      "name": "Karolann Heels",
      "slogan": "Commodi repellat aut animi architecto veniam exercitationem.",
      "description": "Voluptates voluptatibus error quia. Non molestiae esse id fuga omnis itaque mollitia. Iusto ex harum. Sunt fuga rerum voluptate animi eius ipsa quod voluptatem quia. Sed doloribus delectus exercitationem debitis quaerat.",
      "category": "Heels",
      "default_price": "787.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25203,
      "campus": "hr-sfo",
      "name": "Jayme Shoes",
      "slogan": "Consequuntur necessitatibus nostrum qui tempora quis perspiciatis.",
      "description": "Repellendus libero natus magni. A eligendi voluptates omnis et odit dolorum. Quod perferendis doloremque maiores sed at veniam enim. Nostrum voluptatibus quaerat dolores est quia voluptas aut mollitia. Molestiae consequatur ut hic fugit quis ea quidem.",
      "category": "Shoes",
      "default_price": "768.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25204,
      "campus": "hr-sfo",
      "name": "Catharine Tank Top",
      "slogan": "Nisi magni in aut voluptatibus quasi voluptatum.",
      "description": "Et eum ipsa cum debitis reiciendis ut et. Eum ab dicta temporibus atque ipsum dolores. Eum id a qui quidem voluptatibus.",
      "category": "Tank Top",
      "default_price": "131.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25205,
      "campus": "hr-sfo",
      "name": "Sven Skirt",
      "slogan": "Rerum voluptatum et laudantium voluptatum praesentium consequuntur qui.",
      "description": "Est enim illum. Velit perspiciatis eos accusamus porro. Nostrum aperiam maxime. Vero quia aut quis rerum consectetur quibusdam exercitationem quia. Iste laudantium doloribus qui molestias. Officiis accusantium tempora.",
      "category": "Skirt",
      "default_price": "409.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25206,
      "campus": "hr-sfo",
      "name": "Verdie 250 Sweater",
      "slogan": "Autem quasi voluptatem adipisci dolor similique esse.",
      "description": "Quibusdam quo soluta. Magnam est qui eaque ea minus architecto. Dolorum natus facilis enim. Error assumenda aperiam. Dolorum nam fugit recusandae corporis nisi aperiam eaque.",
      "category": "Sweater",
      "default_price": "850.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25207,
      "campus": "hr-sfo",
      "name": "Salma Sunglasses",
      "slogan": "Eaque maxime ratione voluptatibus quae error qui.",
      "description": "Quia amet cumque eius. Doloribus velit debitis porro esse distinctio. Aut voluptas nihil magni consequatur rerum possimus aut.",
      "category": "Sunglasses",
      "default_price": "576.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25208,
      "campus": "hr-sfo",
      "name": "Blake Cap",
      "slogan": "Non delectus pariatur voluptatem esse illum.",
      "description": "Maiores et nihil explicabo pariatur officia. Et harum suscipit eaque enim voluptatibus asperiores. Non facilis excepturi odio. Adipisci deserunt quas omnis soluta rerum omnis.",
      "category": "Cap",
      "default_price": "237.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25209,
      "campus": "hr-sfo",
      "name": "Abigayle Sweatpants",
      "slogan": "Nihil debitis consequuntur tenetur qui quos.",
      "description": "Provident et voluptas tempore optio tenetur ut. Aspernatur et quibusdam at. Iure facilis commodi sunt. Veritatis vel non iusto voluptatibus eaque et consequuntur doloribus. Cumque exercitationem cupiditate eveniet. Tempora debitis et labore.",
      "category": "Sweatpants",
      "default_price": "393.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25210,
      "campus": "hr-sfo",
      "name": "Aric Shorts",
      "slogan": "Tempore iure voluptate aut veniam qui omnis modi labore.",
      "description": "Ut non sit porro voluptate quibusdam placeat quas et. Qui possimus repellat voluptatum et distinctio. Voluptas et ad. Laborum vitae sed temporibus.",
      "category": "Shorts",
      "default_price": "68.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25211,
      "campus": "hr-sfo",
      "name": "Dixie Jacket",
      "slogan": "Dolorem laboriosam voluptate ad.",
      "description": "Similique quasi velit fugiat fuga architecto quis iusto iusto aut. Corporis neque aliquid fugit est sapiente qui. Dignissimos culpa sunt.",
      "category": "Jacket",
      "default_price": "493.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25212,
      "campus": "hr-sfo",
      "name": "Maxwell Shirt",
      "slogan": "Molestias et enim adipisci.",
      "description": "Necessitatibus esse et. Nobis odio aspernatur cum laborum nam odio maxime. Id et veniam ex commodi et modi commodi praesentium.",
      "category": "Shirt",
      "default_price": "10.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25213,
      "campus": "hr-sfo",
      "name": "The Yasmine Suit",
      "slogan": "Vero quaerat reprehenderit sit non dolorem distinctio culpa eaque.",
      "description": "Laudantium hic ipsum nostrum reiciendis reprehenderit in dolore consequatur. Eos sapiente vel dolor consequatur. Et distinctio cum quos.",
      "category": "Suit",
      "default_price": "436.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25214,
      "campus": "hr-sfo",
      "name": "Enid Backpack",
      "slogan": "Voluptatum et rerum fuga eius voluptatem fugit earum minima iste.",
      "description": "Molestiae ducimus est dolor ab id eius veniam quis a. Consequatur error fugit sunt sapiente nostrum. Est impedit officia nulla fugiat quidem molestias quidem. Exercitationem repellendus ducimus aliquid a ipsum necessitatibus qui voluptates et. Illum magni totam. Modi iste et magnam quam.",
      "category": "Backpack",
      "default_price": "395.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25215,
      "campus": "hr-sfo",
      "name": "Jerrold Boots",
      "slogan": "Beatae non qui qui illo veniam eaque voluptatum.",
      "description": "Doloremque culpa praesentium. Ut rerum non neque excepturi quia sed. Temporibus non consequuntur aliquid doloribus dolore rerum voluptates quidem. Velit suscipit aut ut at odio dolor.",
      "category": "Boots",
      "default_price": "850.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  },
  {
      "id": 25216,
      "campus": "hr-sfo",
      "name": "Maybell Sunglasses",
      "slogan": "Officiis voluptatem consequatur ipsum officiis.",
      "description": "Odit occaecati sequi voluptas iure. Temporibus eum itaque. Alias deleniti qui dolorum optio in laudantium dolor minus.",
      "category": "Sunglasses",
      "default_price": "887.00",
      "created_at": "2021-06-02T16:53:33.577Z",
      "updated_at": "2021-06-02T16:53:33.577Z"
  }
]